backend:
  name: github
  repo: adrhumphreys/Microsoft.LandingPage # Path to your Github repository
  branch: master # Branch to update

media_folder: "site/static/images" # Folder where user uploaded files should go
public_folder: "images"

collections: # A list of collections the CMS should be able to edit
  - name: "stories" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Story" # Used in the UI, ie.: "New Post"
    folder: "site/content/stories" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "logo", widget: "image", required: false}
      - {label: "Class", name: "class", widget: "string", required: false}
